source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'example' do
  rnpath = '../../node_modules/react-native'
  pod 'React', path: rnpath, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
  ]
  pod 'yoga', path: "#{rnpath}/ReactCommon/yoga"
  pod 'DoubleConversion', podspec: "#{rnpath}/third-party-podspecs"
  pod 'GLog', podspec: "#{rnpath}/third-party-podspecs"
  pod 'Folly', podspec: "#{rnpath}/third-party-podspecs"

  pod 'react-native-google-cast', path: '../../ios/'
  pod 'google-cast-sdk', '~> 3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
