# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeGoogleCast' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'google-cast-sdk'

  target 'ReactNativeGoogleCastTests' do
    inherit! :search_paths
    # Pods for testing
  end

end